import pandas
import pandas as pd

file_name = "products.txt"

#turning replacement strings into bits
tilde = "~".encode()
comma_space = ", ".encode()
semicolon = ";".encode()
double_tilde = "~~".encode()
none = ", None, ".encode()
metered_inhalation = "metered;inhalation".encode()
metered_space = "metered inhalation".encode()
inh_semicolon = "INH;EQ".encode()
inh_slash = "INH/EQ".encode()
inh_zero = "INH;0".encode()
inh_dash_zero = "INH-0".encode()
discn = "DISCN~".encode()
amp = "AMPHETAMINE ASPARTATE; AMPHETAMINE SULFATE; DEXTROAMPHETAMINE SACCHARATE; DEXTROAMPHETAMINE SULFATE".encode()
amp_edited = "AMPHETAMINE ASPARTATE/AMPHETAMINE SULFATE/DEXTROAMPHETAMINE SACCHARATE/DEXTROAMPHETAMINE SULFATE".encode()
dext = "DEXTROAMP SACCHARATE, AMP ASPARTATE, DEXTROAMP SULFATE AND AMP SULFATE".encode()
dext_edited = "DEXTROAMP SACCHARATE-AMP ASPARTATE-DEXTROAMP SULFATE AND AMP SULFATE".encode()
mg_semicolon = "MG;".encode()
cap_ex = "CAPSULE, EXTENDED RELEASE".encode()
cap_ex_edited = "CAPSULE: EXTENDED RELEASE".encode()
besy = "BESYLATE; BENAZEPRIL".encode()
besy_edited = "BESYLATE/BENAZEPRIL".encode()
ac = "ACETAMINOPHEN; BUTALBITAL; CAFFEINE".encode()
ac_edited = "ACETAMINOPHEN/BUTALBITAL/CAFFEINE".encode()
ac_caf = "ACETAMINOPHEN; BUTALBITAL; CAFFEINE;".encode()
ac_caf_edited = "ACETAMINOPHEN/BUTALBITAL/CAFFEINE/".encode()
asp = "ASPIRIN; BUTALBITAL; CAFFEINE; CODEINE PHOSPHATE".encode()
asp_edited = "ASPIRIN/BUTALBITAL/CAFFEINE/CODEINE PHOSPHATE".encode()
cream_vaginal = "CREAM;TOPICAL, VAGINAL".encode()
cream_vaginal_edited = "CREAM;TOPICAL:VAGINAL".encode()
percent = "%;".encode()
percent_edited = "%-".encode()
bot = "BOT;".encode()
bot_edited = "BOT-".encode()
ml = "ML;".encode()
ml_edited = "ML-".encode()
sodium = "SODIUM; ".encode()
sodium_edited = "SODIUM/".encode()
amino = "AMINO ACIDS; CALCIUM CHLORIDE; DEXTROSE; MAGNESIUM CHLORIDE; POTASSIUM PHOSPHATE, DIBASIC; SODIUM ACETATE; SODIUM CHLORIDE".encode()
amino_edited = "AMINO ACIDS/CALCIUM CHLORIDE/DEXTROSE/MAGNESIUM CHLORIDE/POTASSIUM PHOSPHATE-DIBASIC/SODIUM ACETATE/SODIUM CHLORIDE".encode()
dextrose = "DEXTROSE; ".encode()
dextrose_edited = "DEXTROSE/".encode()
potassium = "POTASSIUM CHLORIDE; ".encode()
potassium_edited = "POTASSIUM CHLORIDE/".encode()
epi = "EPINEPHRINE; ".encode()
epi_edited = "EPINEPHRINE/".encode()
calcium = "CALCIUM CHLORIDE; ".encode()
calcium_edited = "CALCIUM CHLORIDE/".encode()
sodium_chloride = "SODIUM CHLORIDE; ".encode()
sodium_chloride_edited = "SODIUM CHLORIDE/".encode()
lactic = "LACTIC ACID;".encode()
lactic_edited = "LACTIC ACID/".encode()
mag = "MAGNESIUM CHLORIDE; ".encode()
mag_edited = "MAGNESIUM CHLORIDE/".encode()
sodium_bi = "SODIUM BICARBONATE; ".encode()
sodium_bi_edited = "SODIUM BICARBONATE/".encode()
potassium_pho = "POTASSIUM PHOSPHATE, DIBASIC;".encode()
potassium_pho_edited = "POTASSIUM PHOSPHATE-DIBASIC/".encode()
sodium_ac = "SODIUM ACETATE; ".encode()
sodium_ac_edited = "SODIUM ACETATE/".encode()
gm = "GM;".encode()
gm_edited = "GM-".encode()
ny = "NYSTATIN; ".encode()
ny_edited = "NYSTATIN/".encode()
hydro = "HYDROCHLORIDE; ".encode()
hydro_edited = "HYDROCHLORIDE/".encode()
phosphate = "PHOSPHATE; ".encode()
phosphate_edited = "PHOSPHATE/".encode()
sulfate = "SULFATE; ".encode()
sulfate_edited = "SULFATE/".encode()
aspartate = "ASPARTATE; ".encode()
aspartate_edited = "ASPARTATE/".encode()
intravenous = "INTRAVENOUS, ".encode()
intravenous_edited = "INTRAVENOUS-".encode()
intramuscular = "INTRAMUSCULAR, ".encode()
intramuscular_edited = "INTRAMUSCULAR-".encode()
subc = "SUBCUTANEOUS, ".encode()
subc_edited = "SUBCUTANEOUS-".encode()
intraves = "INTRAVESICULAR, ".encode()
intraves_edited = "INTRAVESICULAR-".encode()
spray = "SPRAY;".encode()
spray_edited = "SPRAY-".encode()
hydroc = "HYDROCORTISONE; ".encode()
hydroc_edited = "HYDROCORTISONE/".encode()
maleate = "MALEATE; ".encode()
maleate_edited = "MALEATE/".encode()
hydrob = "HYDROBROMIDE; ".encode()
hydrob_edited = "HYDROBROMIDE/".encode()
amox = "AMOXICILLIN; ".encode()
amox_edited = "AMOXICILLIN/".encode()
carbonate = "CARBONATE; ".encode()
carbonate_edited = "CARBONATE/".encode()
base = "BASE;".encode()
base_edited = "BASE-".encode()
carbidopa = "CARBIDOPA; ".encode()
carbidopa_edited = "CARBIDOPA/".encode()
edition = "Edition, 1.8 Description of Special Situations,".encode()
edition_edited = "Edition 1.8 Description of Special Situations".encode()
ab = "AB1,AB2,AB3,".encode()
ab_edited = "AB1-AB2-AB3-".encode()
ab2 = "AB1,AB2,AB3".encode()
ab2_edited = "AB1-AB2-AB3".encode()
mg_comma = "MG,".encode()
mg_comma_edited = "MG-".encode()

#opening txt file and replacing strings
with open(file_name, "rb") as file:
    data = file.read()
    data = data.replace(base, base_edited)
    data = data.replace(ab, ab_edited)
    data = data.replace(ab2, ab2_edited)
    data = data.replace(mg_comma, mg_comma_edited)
    data = data.replace(edition, edition_edited)
    data = data.replace(carbidopa, carbidopa_edited)
    data = data.replace(bot, bot_edited)
    data = data.replace(hydroc, hydroc_edited)
    data = data.replace(hydrob, hydrob_edited)
    data = data.replace(amox, amox_edited)
    data = data.replace(carbonate, carbonate_edited)
    data = data.replace(spray, spray_edited)
    data = data.replace(maleate, maleate_edited)
    data = data.replace(intravenous, intravenous_edited)
    data = data.replace(intraves, intraves_edited)
    data = data.replace(intramuscular, intramuscular_edited)
    data = data.replace(subc, subc_edited)
    data = data.replace(aspartate, aspartate_edited)
    data = data.replace(hydro, hydro_edited)
    data = data.replace(phosphate, phosphate_edited)
    data = data.replace(sulfate, sulfate_edited)
    data = data.replace(gm, gm_edited)
    data = data.replace(sodium_ac, sodium_ac_edited)
    data = data.replace(potassium_pho, potassium_pho_edited)
    data = data.replace(ml, ml_edited)
    data = data.replace(mag, mag_edited)
    data = data.replace(sodium_bi, sodium_bi_edited)
    data = data.replace(lactic, lactic_edited)
    data = data.replace(inh_semicolon, inh_slash)
    data = data.replace(inh_zero, inh_dash_zero)
    data = data.replace(discn, "".encode())
    data = data.replace(amino, amino_edited)
    data = data.replace(epi, epi_edited)
    data = data.replace(dextrose, dextrose_edited)
    data = data.replace(calcium, calcium_edited)
    data = data.replace(sodium_chloride, sodium_chloride_edited)
    data = data.replace(potassium, potassium_edited)
    data = data.replace(metered_inhalation, metered_space)
    data = data.replace(amp, amp_edited)
    data = data.replace(dext, dext_edited)
    data = data.replace(sodium, sodium_edited)
    data = data.replace(mg_semicolon, "MG-".encode())
    data = data.replace(cap_ex, cap_ex_edited)
    data = data.replace(besy, besy_edited)
    data = data.replace(ac, ac_edited)
    data = data.replace(percent, percent_edited)
    data = data.replace(ac_caf, ac_caf_edited)
    data = data.replace(asp, asp_edited)
    data = data.replace(cream_vaginal, cream_vaginal_edited)
    data = data.replace(double_tilde, none)
    data = data.replace(tilde, comma_space)
    data = data.replace(semicolon, comma_space)




#creating a new file for the edited version
edited_file = "products_edited.txt"

#writing to the edited file
with open(edited_file, "wb") as file:
    file.write(data)


#converting to csv
read_file = pd.read_csv(edited_file)
read_file.to_csv("products.csv", index=None)

selcols = [' appNo', 'activeIngredient', ' proprietaryName', ' dosageForm', ' route', ' RLD', ' RS']

print(read_file.columns)
df=pandas.read_csv("products.csv", usecols=selcols)

df.to_csv("FDAListProducts.csv", index=None, columns=[' appNo', 'activeIngredient', ' proprietaryName', ' dosageForm', ' route', ' RLD', ' RS'])
